# Thanks for Grunt for template of this file!

# http://www.appveyor.com/docs/appveyor-yml

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "4.0"
    - nodejs_version: "4.1"
    - nodejs_version: "5.0"

# Install scripts. (runs after repo cloning)
install:
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - ps: npm test
  - ps: powershell.exe ".\test\test.ps1"

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
